export const CATALOG_SECTORS = [
  { id: "agricultural", label: "Agricultural Operations" },
  { id: "wildlife", label: "Wildlife & Surveillance" },
  { id: "realestate", label: "Real Estate & Surveillance" },
  { id: "evtol", label: "eVTOL" },
];

export const PLATFORM_SECTORS = CATALOG_SECTORS.filter((sector) => sector.id !== "evtol");

// Purchase-first catalogue data. Prices and availability are intentionally
// represented as enquiry-based until the commercial values are confirmed.
export const PRODUCTS = [
  {
    id: "zam13e",
    sector: "evtol",
    name: "ZAM13E Fixed Wing UAV Forest Survey Drone",
    description:
      "Long-range fixed-wing survey UAV for forest survey and general unmanned aerial vehicle operations.",
    spec: "Model: ZAM13E",
    tags: ["Commercial Drone", "Electric", "Fixed Wing", "Survey"],
    availability: "Enquire to purchase",
    specs: [
      ["Drone Type", "Commercial Drones"],
      ["Maximum Flight Time", "Customizable"],
      ["Image Transmission", "1KM"],
      ["Functions", "Altitude Hold, One Key Takeoff/Landing, APP Control"],
      ["Operator Skill Level", "Beginner"],
      ["Control Type", "Remote Control"],
      ["Gyro", "Yes"],
      ["Material", "Wood"],
      ["Place of Origin", "Lusaka, Zambia"],
      ["Private Mold", "Yes"],
      ["Product Name", "General Purpose Aerial Platform"],
      ["Engine Type", "Electric"],
      ["Wingspan", "2700mm"],
      ["Package Size", "120 x 45 x 50 cm"],
      ["Gross Weight", "70kg"],
    ],
  },
  {
    id: "zam2001",
    sector: "evtol",
    name: "ZAM2001 8K GPS Camera Cargo UAV",
    description:
      "Professional GPS camera drone with 8K imaging positioning for efficient commercial and cargo UAV applications.",
    spec: "Model: ZAM2001",
    tags: ["Commercial Drone", "8K Camera", "GPS", "Cargo UAV"],
    availability: "MOQ: 1 set",
    specs: [
      ["Drone Type", "Commercial Drones"],
      ["Maximum Flight Time", "31-40min"],
      ["Image Transmission", "1KM"],
      ["Functions", "Altitude Hold, One Key Takeoff/Landing, APP Control"],
      ["Operator Skill Level", "Beginner"],
      ["Control Type", "Remote Control"],
      ["Gyro", "Yes"],
      ["Material", "Wood"],
      ["Place of Origin", "Lusaka, Zambia"],
      ["Private Mold", "Yes"],
      ["Product Name", "XH15E Drone Camera Drone 8K Professional Efficient GPS UAV Cargo UAV"],
      ["Engine Type", "Electric"],
      ["Package Size", "120 x 45 x 50 cm"],
      ["Gross Weight", "70kg"],
    ],
  },
  {
    id: "zam201",
    sector: "evtol",
    name: "ZAM201 VTOL Fixed-Wing Training Survey Drone",
    description:
      "Electric VTOL general-purpose fixed-wing aircraft for training, surveying, and remote-control UAV operations.",
    spec: "Model: ZAM201",
    tags: ["Commercial Drone", "VTOL", "Electric", "Waterproof"],
    availability: "MOQ: 1 set",
    specs: [
      ["Drone Type", "Commercial Drones"],
      ["Maximum Flight Time", "Customizable"],
      ["Image Transmission", "1KM"],
      ["Functions", "Altitude Hold, One Key Takeoff/Landing, APP Control, Remote Control"],
      ["Operator Skill Level", "Beginner"],
      ["Control Type", "Remote Control"],
      ["Gyro", "Yes"],
      ["Material", "Wood"],
      ["Place of Origin", "Lusaka, Zambia"],
      ["Private Mold", "Yes"],
      ["Product Name", "General Purpose Aerial Platform"],
      ["Engine Type", "Electric"],
      ["Feature", "Waterproof"],
      ["Image Capture Resolution", "Not applicable"],
      ["Indoor Hover", "No"],
      ["Power", "Electric Power"],
    ],
  },
  {
    id: "zam112",
    sector: "evtol",
    name: "ZAM112 Agricultural UAV for Crop Management",
    description:
      "Agricultural unmanned aerial vehicle configured for efficient crop management and commercial farm support.",
    spec: "Model: ZAM112",
    tags: ["Commercial Drone", "Agriculture", "Electric", "Crop Management"],
    availability: "Enquire to purchase",
    specs: [
      ["Drone Type", "Commercial Drones"],
      ["Maximum Flight Time", "31-40min"],
      ["Image Transmission", "1KM"],
      ["Functions", "Altitude Hold, One Key Takeoff/Landing, APP Control"],
      ["Operator Skill Level", "Beginner"],
      ["Control Type", "Remote Control"],
      ["Gyro", "Yes"],
      ["Material", "Wood"],
      ["Place of Origin", "Lusaka, Zambia"],
      ["Private Mold", "Yes"],
      ["Product Name", "General Purpose Aerial Platform"],
      ["Engine Type", "Electric"],
      ["Wingspan", "2700mm"],
      ["Package Size", "120 x 45 x 50 cm"],
      ["Gross Weight", "70kg"],
    ],
  },
  {
    id: "zam237",
    sector: "evtol",
    name: "ZAM237 Carbon Fiber Fixed-Wing Drone Kit",
    description:
      "Carbon-fiber drone airframe kit for long-distance missions, large-drone builds, and cargo delivery applications.",
    spec: "Model: ZAM237",
    tags: ["Beginner Drone", "Carbon Fiber", "Cargo Delivery", "Airframe Kit"],
    availability: "MOQ: 1pc",
    specs: [
      ["Drone Type", "Beginner Drones"],
      ["Maximum Flight Time", "10min or less"],
      ["Image Transmission", "2KM"],
      ["Function", "Altitude Hold Mode"],
      ["Operator Skill Level", "Beginner"],
      ["Control Type", "Remote Control"],
      ["Still Image Resolution", "2 Megapixels"],
      ["Motor", "Brush Motor"],
      ["Gyro", "2-axis"],
      ["Material", "Carbon Fiber for Polymer Materials"],
      ["Place of Origin", "Lusaka, Zambia"],
      ["Private Mold", "Yes"],
      ["Product Name", "Drone Airframe"],
      ["Color", "Customized Color"],
      ["Application", "Cargo Delivery"],
      ["Takeoff Mode", "Sliding Take-off"],
    ],
  },
  {
    id: "zam223-aw1749",
    sector: "evtol",
    name: "ZAM223 / AW1749 Gasoline VTOL Fixed Wing Drone",
    description:
      "3.25m gasoline VTOL fixed-wing aircraft kit for high-payload, long-range outdoor survey missions.",
    spec: "Model: AW1749",
    tags: ["VTOL", "Gas Power", "RTK", "Long Range Survey"],
    availability: "Enquire to purchase",
    specs: [
      ["Place of Origin", "Lusaka, Zambia"],
      ["Remote Distance", "Depends on remote controller battery"],
      ["Material", "Carbon Fiber"],
      ["Features", "RTK"],
      ["Video Capture Resolution", "None"],
      ["Operator Skill Level", "Expert"],
      ["Use", "Outdoor"],
      ["State of Assembly", "Unassembled Kit"],
      ["Aerial Photography", "Yes"],
      ["Power Source", "Gas"],
      ["Age Range", "14 Years & up"],
    ],
  },
  {
    id: "aw1338",
    sector: "evtol",
    name: "AW1338 HD 4K Long Distance Mapping Drone",
    description:
      "Long-distance fixed-wing mapping UAV with HD 4K camera, GPS remote-control features, and carbon-fiber airframe.",
    spec: "Model: AW1338",
    tags: ["4K Camera", "GPS", "Mapping", "Carbon Fiber"],
    availability: "Enquire to purchase",
    specs: [
      ["Operator Skill Level", "Beginner"],
      ["Control Type", "Remote Control"],
      ["Model Number", "V3000"],
      ["Gyro", "Consult customer service"],
      ["Material", "Carbon Fiber"],
      ["Place of Origin", "Lusaka, Zambia"],
      ["Private Mold", "No"],
      ["Wingspan", "3600mm"],
      ["Fuselage Length", "1800mm"],
      ["Payload", "2-2.5kg"],
      ["Wind Resistance", "Lv.5"],
      ["Cruising Speed", "20m/s"],
      ["Practical Ceiling", "5000m"],
      ["Application", "Mapping"],
    ],
  },
  {
    id: "aw50g",
    sector: "agricultural",
    name: "Nkem AW50G High-Payload Agri Sprayer",
    description:
      "16L capacity electric spraying UAV built for large-scale crop protection, liquid fertilizer deployment, and automated flight paths.",
    spec: "Payload: 16 Liters",
    tags: ["Agricultural", "Spraying", "Electric"],
    crops: ["grains", "plantation"],
    service: "spraying",
  },
  {
    id: "awv2548",
    sector: "agricultural",
    name: "Nkem AWV2548 Ultralight Agri Drone",
    description:
      "10L folding multi-rotor sprayer frame under 10kg, optimized for rapid field deployment and localized vegetable farm spraying.",
    spec: "Frame: Cross-Foldable",
    tags: ["Agricultural", "Spraying", "Foldable"],
    crops: ["vegetables"],
    service: "spraying",
  },
  {
    id: "awv2847",
    sector: "agricultural",
    name: "Nkem AWV2847 Efficient Crop Monitor",
    description:
      "Multispectral drone system built for early plant disease detection, soil moisture mapping, and yield estimation across grains.",
    spec: "Type: Multispectral UAV",
    tags: ["Agricultural", "Monitoring", "Multispectral"],
    crops: ["grains", "plantation", "vegetables"],
    service: "both",
  },
  // Ground robots (ground-based, not aerial) — client-supplied spec sheet.
  // "Maximum Gradeability" read as 20° per the client's own document note; worth a final confirmation.
  {
    id: "gr-spray-140l",
    sector: "agricultural",
    name: "140L Heavy-Duty Agri Spraying Robot (6-Wheel)",
    description:
      "Variable-rate ground spraying robot: spray volume adapts to movement speed, ensuring crops receive the right amount with minimal waste.",
    image: "/images/ground-robots/140l-heavy-duty-spraying-robot.jpg",
    spec: "Tank Capacity: 140 L",
    tags: ["Agricultural", "Ground Robot", "Spraying"],
    crops: ["grains", "plantation", "vegetables"],
    service: "machines",
    specs: [
      ["Tank Capacity", "140 L"],
      ["Maximum Flow Rate", "16 L/min"],
      ["Droplet Size", "120–400 μm"],
      ["Maximum Horizontal Range Per Side", "34 m"],
      ["Vehicle Width", "80 cm"],
      ["Curb Weight", "160 kg"],
      ["Maximum Travel Speed", "3 m/s"],
      ["Maximum Gradeability", "20°"],
    ],
  },
  {
    id: "gr-spray-120l",
    sector: "agricultural",
    name: "120L Compact Agri Spraying Robot (4-Wheel)",
    description:
      "Variable-rate ground spraying robot: spray volume adapts to movement speed, ensuring crops receive the right amount with minimal waste.",
    image: "/images/ground-robots/120l-compact-spraying-robot.jpg",
    spec: "Tank Capacity: 120 L",
    tags: ["Agricultural", "Ground Robot", "Spraying"],
    crops: ["grains", "plantation", "vegetables"],
    service: "machines",
    specs: [
      ["Tank Capacity", "120 L"],
      ["Maximum Flow Rate", "8 L/min"],
      ["Droplet Size", "60–200 μm"],
      ["Maximum Horizontal Range Per Side", "17 m"],
      ["Vehicle Width", "80 cm"],
      ["Curb Weight", "80 kg"],
      ["Maximum Travel Speed", "1.5 m/s"],
      ["Maximum Gradeability", "20°"],
    ],
  },
  {
    id: "gr-crawler-transport",
    sector: "agricultural",
    name: "Crawler Transport Vehicle (Remote-Controlled)",
    description:
      "Remote-controlled tracked transport vehicle for hauling loads across farm terrain.",
    image: "/images/ground-robots/crawler-transport-vehicle.jpg",
    spec: "Load Capacity: 1.8 T",
    tags: ["Agricultural", "Ground Robot", "Transport"],
    crops: ["grains", "plantation", "vegetables"],
    service: "machines",
    specs: [
      ["Machine Size", "1800 × 1200 × 450 mm"],
      ["Machine Weight", "450 kg"],
      ["Climbing Ability", "< 45°"],
      ["Load Capacity", "1.8 T"],
      ["Machine Power (Li-ion)", "130 AH"],
      ["Track Width", "180 mm"],
      ["Control Mode (RC)", "Remote distance 200 m"],
      ["Travel Motor", "1200 W × 2"],
      ["Travel Speed", "20–70 m/min"],
      ["Run Time", "8 h"],
    ],
  },
  {
    id: "gr-dumpcart",
    sector: "agricultural",
    name: "DumpCart (Crawler Dump Vehicle)",
    description:
      "Remote-controlled tracked dump vehicle for hauling and unloading materials on farm sites.",
    image: "/images/ground-robots/dumpcart-dump-vehicle.jpg",
    spec: "Load Capacity: 1.8 T",
    tags: ["Agricultural", "Ground Robot", "Dump Cart"],
    crops: ["grains", "plantation", "vegetables"],
    service: "machines",
    specs: [
      ["Machine Size", "1800 × 1200 × 1200 mm"],
      ["Machine Weight", "600 kg"],
      ["Climbing Ability", "< 45°"],
      ["Load Capacity", "1.8 T"],
      ["Machine Power (Li-ion)", "130 AH"],
      ["Track Width", "180 mm"],
      ["Control Mode (RC)", "Remote distance 200 m"],
      ["Travel Motor", "1500 W × 2"],
      ["Travel Speed", "20–70 m/min"],
      ["Run Time", "8 h"],
    ],
  },
  {
    id: "aw1749",
    sector: "wildlife",
    name: "Nkem AW1749 Gasoline VTOL Fixed-Wing",
    description:
      "3.25m wingspan long-range vertical takeoff drone for extended national park surveillance and mapping.",
    spec: "Range: High Range VTOL",
    tags: ["Wildlife", "VTOL", "Long Range"],
  },
  {
    id: "awv2555",
    sector: "wildlife",
    name: "Nkem AWV2555 Tethered Security Unit",
    description:
      "Continuous-power tethered UAV providing emergency lighting and uninterrupted camera overwatch.",
    spec: "Power: Tethered Cable",
    tags: ["Security", "Tethered", "Continuous Power"],
  },
  {
    id: "aw1338-wildlife",
    sector: "wildlife",
    name: "Nkem AW1338 HD Mapping Remote UAV",
    description: "4K camera GPS platform designed for thermal wildlife tracking and border surveillance.",
    spec: "Optics: 4K HD Gimbal",
    tags: ["Wildlife", "4K", "GPS"],
  },
];
