export const catalogProducts = [
  {
    id: "zam13e",
    sector: "evtol",
    name: "ZAM13E Fixed Wing UAV Forest Survey Drone",
    type: "Commercial Drones",
    model: "ZAM13E",
    engineType: "Electric",
    availability: "Enquire to purchase",
    price: null,
  },
  {
    id: "zam2001",
    sector: "evtol",
    name: "ZAM2001 8K GPS Camera Cargo UAV",
    type: "Commercial Drones",
    model: "ZAM2001",
    engineType: "Electric",
    availability: "MOQ: 1 set",
    price: null,
  },
  {
    id: "zam201",
    sector: "evtol",
    name: "ZAM201 VTOL Fixed-Wing Training Survey Drone",
    type: "Commercial Drones",
    model: "ZAM201",
    engineType: "Electric",
    availability: "MOQ: 1 set",
    price: null,
  },
  {
    id: "zam112",
    sector: "evtol",
    name: "ZAM112 Agricultural UAV for Crop Management",
    type: "Commercial Drones",
    model: "ZAM112",
    engineType: "Electric",
    availability: "Enquire to purchase",
    price: null,
  },
  {
    id: "zam237",
    sector: "evtol",
    name: "ZAM237 Carbon Fiber Fixed-Wing Drone Kit",
    type: "Beginner Drones",
    model: "ZAM237",
    engineType: null,
    availability: "MOQ: 1pc",
    price: null,
  },
  {
    id: "zam223-aw1749",
    sector: "evtol",
    name: "ZAM223 / AW1749 Gasoline VTOL Fixed Wing Drone",
    type: "VTOL Fixed Wing",
    model: "AW1749",
    engineType: "Gas",
    availability: "Enquire to purchase",
    price: null,
  },
  {
    id: "aw1338",
    sector: "evtol",
    name: "AW1338 HD 4K Long Distance Mapping Drone",
    type: "Mapping UAV",
    model: "AW1338",
    engineType: null,
    availability: "Enquire to purchase",
    price: null,
  },
];
